name: Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  Deploy-to-Heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "odus-telegram-message-service"
          heroku_email: "ilya@zobenko.ru"
        env:
          NODE_ENV: production
          HTTP_ADDR: "0.0.0.0"
          PORT: 80
          HTTP_TIMEOUT: 2
